### ISSUE TITLE
Pagination seems to be broken

### ISSUE THREAD

**Issue by jakeols** [champsupertramp/Ajaxify-Ultimatemember-Search-Form#1]
Hi,

I just found this plugin. Everything seems to be working fine except the pagination. It seems to be appending the search results to the current member list instead of replacing it. 

An example is after searching when the form is reset, it loads each member profile twice. 

I forked the project to see if I can fix it- I'm assuming this is all handled in the aumd-public pagination function? 

Thanks

Created a PR for this here - #2

**Comment by champsupertramp** [comment]
Hi,

Thanks for the fixes.

Regards,
